import 'package:top_ten/car_model/car_object.dart';
import 'package:top_ten/object_lists/car_details_list.dart';
final List<CarObject> carModelsLists = [
  CarObject(
    carId: 0,
    carName: 'Chevrolet-Equinox',
    price: '28600\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '5',
    warranty: '3 years / 36k miles',
    imgSrc: 'assets/images/chevrolet-equinox.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/equ0.jpg',
      'assets/images/sliderImgs/equ1.jpg',
      'assets/images/sliderImgs/equ2.jpg',
    ],
    carDetails: carDetailsList[0],
  ),
  CarObject(
    carDetails: carDetailsList[1],
    carId: 1,
    carName: 'Honda-Accord',
    price: '24560\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '5',
    warranty: '5 years / 60k miles',
    imgSrc: 'assets/images/honda-accord.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/honda0.png',
      'assets/images/sliderImgs/honda1.png',
      'assets/images/sliderImgs/honda2.png',
    ],
  ),
  CarObject(
      carDetails: carDetailsList[2],
      carId: 2,
      carName: 'Honda-Civic',
      price: '34056\$',
      engin: 'Gas',
      horsepower: '123 - 145 hp',
      seating: '5',
      warranty: '5 years / 20k miles',
      imgSrc: 'assets/images/honda-civic.jpg',
      caroselImgs: [
        'assets/images/sliderImgs/civic0.png',
        'assets/images/sliderImgs/civic1.png',
        'assets/images/sliderImgs/civic2.png',
      ]),
  CarObject(
    carDetails: carDetailsList[3],
    carId: 3,
    carName: 'Jeep-Grand',
    price: '98056\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '4',
    warranty: '1 years / 610k miles',
    imgSrc: 'assets/images/jeep-grand-cherokee.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/jeep0.png',
          'assets/images/sliderImgs/jeep1.png',
          'assets/images/sliderImgs/jeep2.png',
    ],
  ),
  CarObject(
    carDetails: carDetailsList[4],
    carId: 4,
    carName: 'Nissan-Sentra',
    price: '12343\$',
    engin: 'Gas',
    horsepower: '123 - 200 hp',
    seating: '5',
    warranty: '3 years / 90k miles',
    imgSrc: 'assets/images/nissan-santra.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/santra0.png',
      'assets/images/sliderImgs/santra2.png',
      'assets/images/sliderImgs/sentra1.png',
    ],
  ),
  CarObject(
    carDetails: carDetailsList[5],
    carId: 5,
    carName: 'Subaru-Forester',
    price: '20756\$',
    engin: 'Petrol',
    horsepower: '12 - 345 hp',
    seating: '2',
    warranty: '9 years / 90k miles',
    imgSrc: 'assets/images/subaru-forester.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/subaru0.png',
      'assets/images/sliderImgs/subaru1.png',
      'assets/images/sliderImgs/subaru2.png',
    ],
  ),
  CarObject(
    carDetails: carDetailsList[6],
    carId: 6,
    carName: 'Tesla-Model-Y',
    price: '23466\$',
    engin: 'Gas',
    horsepower: '45 - 145 hp',
    seating: '3',
    warranty: '2 years/ 345km',
    imgSrc: 'assets/images/tesla-model-y.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/tesla0.png',
      'assets/images/sliderImgs/Tesla1.png',
      'assets/images/sliderImgs/Tesla2.png',
    ],
  ),
  CarObject(
    carDetails: carDetailsList[7],
    carId: 7,
    carName: 'Toyota-Camry',
    price: '67456\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '4',
    warranty: '1 years / 30k miles',
    imgSrc: 'assets/images/toyota-camry.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/camry0.png',
      'assets/images/sliderImgs/camry1.png',
      'assets/images/sliderImgs/camry2.png',
    ],
  ),
  CarObject(
    carDetails: carDetailsList[8],
    carId: 8,
    carName: 'Toyota-GR-Corolla',
    price: '249756\$',
    engin: 'Solar',
    horsepower: '23 - 175 hp',
    seating: '5',
    warranty: '4 years/ 345km',
    imgSrc: 'assets/images/toyota-gr-corolla.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/gr0.png',
      'assets/images/sliderImgs/gr1.png',
      'assets/images/sliderImgs/gr2.png',
    ],
  ),
  CarObject(
    carDetails: carDetailsList[9],
    carId: 9,
    carName: 'Toyota-Rav4',
    price: '45600\$',
    engin: 'Gas',
    horsepower: '654 - 9987 hp',
    seating: '5',
    warranty: '6 years/ 345km',
    imgSrc: 'assets/images/toyota-rav4.jpg',
    caroselImgs: [
      'assets/images/sliderImgs/rav0.png',
      'assets/images/sliderImgs/rav1.png',
      'assets/images/sliderImgs/rav2.png',
    ],
  )
];
