import 'package:top_ten/car_model/car_object.dart';

final List<CarObject> carModelsLists = [
  CarObject(
    carId: 0,
    carName: 'Chevrolet-Equinox',
    price: '28600\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '5',
    warranty: '3 years / 36k miles',
    imgSrc: 'assets/images/chevrolet-equinox.jpg',
  ),
  CarObject(
    carId: 1,
    carName: 'Honda-Accord',
    price: '24560\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '5',
    warranty: '5 years / 60k miles',
    imgSrc: 'assets/images/honda-accord.jpg',
  ),
  CarObject(
    carId: 2,
    carName: 'Honda-Civic',
    price: '34056\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '5',
    warranty: '5 years / 20k miles',
    imgSrc: 'assets/images/honda-civic.jpg',
  ),
  CarObject(
    carId: 3,
    carName: 'Jeep-Grand-Cherokee',
    price: '98056\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '4',
    warranty: '1 years / 610k miles',
    imgSrc: 'assets/images/jeep-grand-cherokee.jpg',
  ),
  CarObject(
    carId: 3,
    carName: 'Nissan-Sentra',
    price: '12343\$',
    engin: 'Gas',
    horsepower: '123 - 200 hp',
    seating: '5',
    warranty: '3 years / 90k miles',
    imgSrc: 'assets/images/nissan-santra.jpg',
  ),
  CarObject(
    carId: 3,
    carName: 'Subaru-Forester',
    price: '20756\$',
    engin: 'Petrol',
    horsepower: '12 - 345 hp',
    seating: '2',
    warranty: '9 years / 90k miles',
    imgSrc: 'assets/images/subaru-forester.jpg',
  ),
  CarObject(
    carId: 3,
    carName: 'Tesla-Model-Y',
    price: '23466\$',
    engin: 'Gas',
    horsepower: '45 - 145 hp',
    seating: '3',
    warranty: '2 years/ 345km',
    imgSrc: 'assets/images/tesla-model-y.jpg',
  ),
  CarObject(
    carId: 3,
    carName: 'Toyota-Camry',
    price: '67456\$',
    engin: 'Gas',
    horsepower: '123 - 145 hp',
    seating: '4',
    warranty: '1 years / 30k miles',
    imgSrc: 'assets/images/toyota-camry.jpg',
  ),
  CarObject(
    carId: 3,
    carName: 'Toyota-GR-Corolla',
    price: '249756\$',
    engin: 'Solar',
    horsepower: '23 - 175 hp',
    seating: '5',
    warranty: '4 years/ 345km',
    imgSrc: 'assets/images/toyota-gr-corolla.jpg',
  ),
  CarObject(
    carId: 3,
    carName: 'Toyota-Rav4',
    price: '45600\$',
    engin: 'Gas',
    horsepower: '654 - 9987 hp',
    seating: '5',
    warranty: '6 years/ 345km',
    imgSrc: 'assets/images/toyota-rav4.jpg',
  )
];
